### ISSUE TITLE
Base de datos Completa

### ISSUE THREAD

**Issue by Atixx** [Atixx/Lecoib#17]
# Muy Gordita
## Debe tener:
- 2 grupos de trabajo
- 2 categorias (id 1 supervisor, id 2 operario/agente/adminasist/araceli)
- 3 turnos
- Por grupo y por turno, 2 agentes y su supervisor (sus categorias)
- Fichadas de un par de empleados desde el origen de los tiempos
- Usuarios (privilegio igual a su categoria(

**Comment by mcolombo87** [comment]
Verificar si esta lo suficientemente gordita. Agrege 3 grupos al final, uno por turno.

Antes de ejecutar el Query recuerden hacer "drop database lecoib;" para evitar problemas con las claves autoincrementables.

**Comment by Atixx** [comment]
Olvida lo que puse antes.
Este si tira error:

La baja logica esta en null, tendria que ser false (0, o lo que sea)

**Comment by mcolombo87** [comment]
Listo
